export * from "./classes";
export * from "./divisions";
export * from "./subjects";
export * from "./syllabus";
export * from "./teachers";
export * from "./assign-teacher";
export * from "./admissions";
export * from "./location-settings";
export * from "./timetable";
